apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patchesStrategicMerge:
- deployment.yaml
- service.yaml

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "mohamed.adil.ibrahim@gmail.com"


configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=ArgoCD
      - OPTION_B=FluxCD
